# Generated by Django 4.2 on 2024-12-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_address_address_alter_address_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='country',
            new_name='nearest_landmark',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
    ]
